
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;
import javax.swing.text.MaskFormatter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author trkgrn
 */
public class BankaMuduru extends javax.swing.JFrame {

    private String mudurTc;
    private int kisiId;
    private User user;

    /**
     * Creates new form BankaMuduru
     */
    public BankaMuduru() {
        initComponents();
    }

    public BankaMuduru(String mudurTc, int kisiId) {
        initComponents();
        setVisible(true);
        this.mudurTc = mudurTc;
        this.kisiId = kisiId;
        initProfile();
        TabloIslem.getInstance().showMusteriTable(musteriTable, 0, 2);
        TabloIslem.getInstance().showParaBirimTable(paraBirimTable);
    }

    private void initProfile() {
        String sorgu = "SELECT * FROM kisi where tc_no='" + mudurTc + "'";
        DBislem dbislem = new DBislem();

        user = dbislem.getUser(sorgu, this);
        Tarih.getInstance();
        tarihLabel.setText(Tarih.myFormat.format(Tarih.getAnlikTarih()));
        bankaGiderTF.setText("" + DBislem.getBankaGider());
        bankaGelirTF.setText("" + DBislem.getBankaGelir());
        mudurAdTF.setText(user.getAd());
        mudurSoyadTF.setText(user.getSoyad());
        mudurTcnoTF.setText(user.getTcNo());
        mudurTelefonTF.setText(user.getTelefon());
        mudurMailTF.setText(user.getePosta());
        mudurAdresTF.setText(user.getAdres());

        mudurAdTF.setEditable(false);
        mudurSoyadTF.setEditable(false);
        mudurTcnoTF.setEditable(false);
        mudurTelefonTF.setEditable(false);
        mudurMailTF.setEditable(false);
        mudurAdresTF.setEditable(false);
        bankaGiderTF.setEditable(false);
        bankaGelirTF.setEditable(false);

        String krediFaizi = "" + DBislem.getFaiz("Kredi Faizi");
        String gecikmeFaizi = "" + DBislem.getFaiz("Gecikme Faizi");
        String maas = "" + DBislem.getTemsilciMaas();
        krediFaiziTF.setText(krediFaizi);
        gecikmeFaiziTF.setText(gecikmeFaizi);
        temsilciMaasTF.setText(maas);
        krediFaiziTF.setEditable(false);
        krediFaiziTF.setEditable(false);
        temsilciMaasTF.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mudurAdTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        mudurSoyadTF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        mudurTcnoTF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        mudurTelefonTF = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        mudurMailTF = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        mudurAdresTF = new javax.swing.JTextField();
        duzenleButton = new javax.swing.JButton();
        kaydetButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        paraBirimTable = new javax.swing.JTable();
        paraBirimAdTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kurFiyatTF = new javax.swing.JTextField();
        pbEkleButton = new javax.swing.JButton();
        pbGuncelleButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        krediFaiziTF = new javax.swing.JTextField();
        jLable = new javax.swing.JLabel();
        gecikmeFaiziTF = new javax.swing.JTextField();
        jLable1 = new javax.swing.JLabel();
        temsilciMaasTF = new javax.swing.JTextField();
        kfDuzenleButton = new javax.swing.JButton();
        gfDuzenleButton = new javax.swing.JButton();
        maasDuzenleButton = new javax.swing.JButton();
        jLable2 = new javax.swing.JLabel();
        jLable3 = new javax.swing.JLabel();
        jLable4 = new javax.swing.JLabel();
        bankaGelirTF = new javax.swing.JTextField();
        bankaGiderTF = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        musteriAdTF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        musteriSoyadTF = new javax.swing.JTextField();
        musteriTcnoTF = new javax.swing.JTextField();
        musteriTelefonTF = new javax.swing.JTextField();
        musteriMailTF = new javax.swing.JTextField();
        musteriAdresTF1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        toplamGelirTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        musteriSifreTF = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        musteriTable = new javax.swing.JTable();
        musteriEkleButton = new javax.swing.JButton();
        musteriGuncelleButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        islemTable = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        goruntuleButton = new javax.swing.JButton();
        islemSayisiTF = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        tarihLabel = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();
        simulationButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel1.setText("Ad");

        mudurAdTF.setEditable(false);
        mudurAdTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mudurAdTFActionPerformed(evt);
            }
        });
        mudurAdTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mudurAdTFKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel12.setText("Soyad");

        mudurSoyadTF.setEditable(false);
        mudurSoyadTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mudurSoyadTFKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel14.setText("TCK No");

        mudurTcnoTF.setEditable(false);
        mudurTcnoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mudurTcnoTFActionPerformed(evt);
            }
        });
        mudurTcnoTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mudurTcnoTFKeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel16.setText("Telefon No");

        mudurTelefonTF.setEditable(false);
        mudurTelefonTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mudurTelefonTFKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel17.setText("E-Posta");

        mudurMailTF.setEditable(false);
        mudurMailTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mudurMailTFActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel18.setText("Adres");

        mudurAdresTF.setEditable(false);

        duzenleButton.setFont(new java.awt.Font("Open Sans", 1, 10)); // NOI18N
        duzenleButton.setText("Düzenle");
        duzenleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duzenleButtonActionPerformed(evt);
            }
        });

        kaydetButton.setFont(new java.awt.Font("Open Sans", 1, 10)); // NOI18N
        kaydetButton.setText("Kaydet");
        kaydetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(mudurTelefonTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGap(114, 114, 114)
                                    .addComponent(mudurSoyadTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(68, 68, 68)
                                .addComponent(mudurTcnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(68, 68, 68)
                                .addComponent(mudurAdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(29, 29, 29)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mudurMailTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mudurAdresTF, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(131, 131, 131))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(duzenleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(kaydetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {mudurAdTF, mudurSoyadTF, mudurTcnoTF, mudurTelefonTF});

        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mudurAdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(mudurSoyadTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mudurTcnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mudurTelefonTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mudurAdresTF, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mudurMailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(87, 87, 87)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kaydetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duzenleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {mudurAdTF, mudurMailTF, mudurSoyadTF, mudurTcnoTF, mudurTelefonTF});

        jTabbedPane1.addTab("Profilim", jPanel7);

        paraBirimTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Para Birim No", "Para Birim Adı", "Kur Sabiti"
            }
        ));
        jScrollPane1.setViewportView(paraBirimTable);

        paraBirimAdTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paraBirimAdTFActionPerformed(evt);
            }
        });
        paraBirimAdTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                paraBirimAdTFKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel2.setText("Para Birim Adı");

        jLabel3.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel3.setText("Kur Fiyatı");

        kurFiyatTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurFiyatTFActionPerformed(evt);
            }
        });
        kurFiyatTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kurFiyatTFKeyTyped(evt);
            }
        });

        pbEkleButton.setFont(new java.awt.Font("Open Sans", 1, 10)); // NOI18N
        pbEkleButton.setText("Ekle");
        pbEkleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbEkleButtonActionPerformed(evt);
            }
        });

        pbGuncelleButton.setFont(new java.awt.Font("Open Sans", 1, 10)); // NOI18N
        pbGuncelleButton.setText("Güncelle");
        pbGuncelleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbGuncelleButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel4.setText("Kredi Faizi");

        krediFaiziTF.setEditable(false);
        krediFaiziTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                krediFaiziTFActionPerformed(evt);
            }
        });

        jLable.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLable.setText("Gecikme Faizi");

        gecikmeFaiziTF.setEditable(false);
        gecikmeFaiziTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gecikmeFaiziTFActionPerformed(evt);
            }
        });

        jLable1.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLable1.setText("Temsilci Maaşı");

        temsilciMaasTF.setEditable(false);
        temsilciMaasTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temsilciMaasTFActionPerformed(evt);
            }
        });

        kfDuzenleButton.setFont(new java.awt.Font("Open Sans", 1, 10)); // NOI18N
        kfDuzenleButton.setText("Düzenle");
        kfDuzenleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kfDuzenleButtonActionPerformed(evt);
            }
        });

        gfDuzenleButton.setFont(new java.awt.Font("Open Sans", 1, 10)); // NOI18N
        gfDuzenleButton.setText("Düzenle");
        gfDuzenleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gfDuzenleButtonActionPerformed(evt);
            }
        });

        maasDuzenleButton.setFont(new java.awt.Font("Open Sans", 1, 10)); // NOI18N
        maasDuzenleButton.setText("Düzenle");
        maasDuzenleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maasDuzenleButtonActionPerformed(evt);
            }
        });

        jLable2.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N

        jLable3.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLable3.setText("Banka Gelir (Aylık)");

        jLable4.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLable4.setText("Banka Gider (Aylık)");

        bankaGelirTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankaGelirTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(paraBirimAdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(pbEkleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(60, 60, 60)
                                    .addComponent(pbGuncelleButton))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(kurFiyatTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLable2)
                        .addGap(257, 257, 257))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(krediFaiziTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(gecikmeFaiziTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLable1)
                                        .addGap(18, 18, 18)
                                        .addComponent(temsilciMaasTF, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kfDuzenleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gfDuzenleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(maasDuzenleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jLable3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLable4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bankaGelirTF)
                                    .addComponent(bankaGiderTF))))
                        .addGap(49, 49, 49))))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {pbEkleButton, pbGuncelleButton});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bankaGelirTF, bankaGiderTF, temsilciMaasTF});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paraBirimAdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLable2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kurFiyatTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pbEkleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pbGuncelleButton))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(krediFaiziTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kfDuzenleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLable, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gecikmeFaiziTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gfDuzenleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLable1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(temsilciMaasTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maasDuzenleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLable3)
                            .addComponent(bankaGelirTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLable4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bankaGiderTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65))))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {pbEkleButton, pbGuncelleButton});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bankaGelirTF, bankaGiderTF, temsilciMaasTF});

        jTabbedPane1.addTab("Banka İşlemleri", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel5.setText("Ad");

        musteriAdTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musteriAdTFActionPerformed(evt);
            }
        });
        musteriAdTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                musteriAdTFKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel13.setText("Soyad");

        jLabel15.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel15.setText("TCK No");

        jLabel19.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel19.setText("Telefon No");

        jLabel20.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel20.setText("E-Posta");

        jLabel21.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel21.setText("Adres");

        musteriSoyadTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                musteriSoyadTFKeyTyped(evt);
            }
        });

        musteriTcnoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musteriTcnoTFActionPerformed(evt);
            }
        });
        musteriTcnoTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                musteriTcnoTFKeyTyped(evt);
            }
        });

        musteriTelefonTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                musteriTelefonTFKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel7.setText("Toplam Gelir");

        toplamGelirTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                toplamGelirTFKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel10.setText("Şifre");

        musteriTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Müşteri No", "Temsilci No", "Ad-Soyad", "TCK No", "Telefon No", "E-Mail Adresi", "Adres", "Toplam Bakiye", "Toplam Gelir"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(musteriTable);

        musteriEkleButton.setFont(new java.awt.Font("Open Sans", 1, 10)); // NOI18N
        musteriEkleButton.setText("Yeni Müşteri Ekle");
        musteriEkleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musteriEkleButtonActionPerformed(evt);
            }
        });

        musteriGuncelleButton.setFont(new java.awt.Font("Open Sans", 1, 10)); // NOI18N
        musteriGuncelleButton.setText("Müşteri Güncelle");
        musteriGuncelleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musteriGuncelleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(musteriEkleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(musteriGuncelleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(290, 290, 290))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15))
                                .addGap(111, 111, 111)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(musteriSoyadTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(musteriTcnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(145, 145, 145)
                                .addComponent(musteriAdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(musteriSifreTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(toplamGelirTF, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(musteriAdresTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(musteriTelefonTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(musteriMailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {musteriEkleButton, musteriGuncelleButton});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(musteriAdTF)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(musteriSoyadTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(musteriTcnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(musteriAdresTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(musteriTelefonTF)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(musteriMailTF)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toplamGelirTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(musteriSifreTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(musteriGuncelleButton)
                    .addComponent(musteriEkleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {musteriEkleButton, musteriGuncelleButton});

        jTabbedPane1.addTab("Müşteri Ekle/Güncelle", jPanel5);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        islemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "İşlem No", "Ad-Soyad", "Kaynak", "Hedef", "İşlem Türü", "İşlem Tutarı", "Kaynak Bakiye", "Hedef Bakiye", "İşlem Tarihi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(islemTable);

        jLabel22.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel22.setText("İşlem Sayısı");

        goruntuleButton.setFont(new java.awt.Font("Open Sans", 1, 10)); // NOI18N
        goruntuleButton.setText("İşlemleri Görüntüle");
        goruntuleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goruntuleButtonActionPerformed(evt);
            }
        });

        islemSayisiTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                islemSayisiTFKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel22)
                .addGap(32, 32, 32)
                .addComponent(islemSayisiTF, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(goruntuleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(343, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(goruntuleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(islemSayisiTF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Geçmiş İşlemler", jPanel3);

        jPanel2.setBackground(new java.awt.Color(102, 51, 255));

        tarihLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        logoutLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\takoy\\Desktop\\Proje-3\\mavenproject1\\src\\main\\java\\com\\mycompany\\mavenproject1\\resim\\logout.png")); // NOI18N
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
        });

        simulationButton.setBackground(new java.awt.Color(255, 255, 255));
        simulationButton.setFont(new java.awt.Font("Open Sans", 1, 10)); // NOI18N
        simulationButton.setText("Simüle Et");
        simulationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(tarihLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(simulationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(logoutLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(tarihLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(simulationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutLabel)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 942, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1118, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void musteriGuncelleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musteriGuncelleButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) musteriTable.getModel();

        if (musteriTable.getSelectedRowCount() == 1) {
            String musteri_id = model.getValueAt(musteriTable.getSelectedRow(), 0).toString();
            int kisi_id = DBislem.getID("Select * from musteri where musteri_id=" + musteri_id, this, "kisi_id");
            String ad = DBislem.getAd("Select * from kisi where kisi_id=" + kisi_id, this, "ad");
            String soyad = DBislem.getAd("Select * from kisi where kisi_id=" + kisi_id, this, "soyad");
            String tcno = model.getValueAt(musteriTable.getSelectedRow(), 2).toString();
            String telefon = model.getValueAt(musteriTable.getSelectedRow(), 3).toString();
            String mail = model.getValueAt(musteriTable.getSelectedRow(), 4).toString();
            String adres = model.getValueAt(musteriTable.getSelectedRow(), 5).toString();

            String newAd = JOptionPane.showInputDialog(null, "Yeni Ad giriniz:", ad);
            String newSoyad = JOptionPane.showInputDialog(null, "Yeni Soyad giriniz:", soyad);
            String newTcno = JOptionPane.showInputDialog(null, "Yeni TCK No giriniz:", tcno);
            String newTel = JOptionPane.showInputDialog(null, "Yeni Telefon Numarası giriniz:", telefon);
            String newMail = JOptionPane.showInputDialog(null, "Yeni Mail Aderesi giriniz:", mail);
            String newAdres = JOptionPane.showInputDialog(null, "Yeni Adres giriniz:", adres);

            String sorgu = "UPDATE kisi\n"
                    + "	SET ad='" + newAd + "', soyad='" + newSoyad + "', tc_no='" + newTcno + "',"
                    + " telefon='" + newTel + "', e_posta='" + newMail + "', adres='" + newAdres + "'\n"
                    + "	WHERE kisi_id=" + kisi_id;
            DBislem.updateQuery(sorgu);

            JOptionPane.showMessageDialog(this, "Müşteri başarıyla güncellendi.");
            TabloIslem.getInstance().showMusteriTable(musteriTable, 0, 2);
        } else {
            JOptionPane.showMessageDialog(this, "Lütfen güncellemek istediğiniz en fazla 1 adet satırı seçin!");
        }
    }//GEN-LAST:event_musteriGuncelleButtonActionPerformed

    private void musteriEkleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musteriEkleButtonActionPerformed
        // TODO add your handling code here:
        String ad = musteriAdTF.getText();
        String soyad = musteriSoyadTF.getText();
        String tcno = musteriTcnoTF.getText();
        String toplamGelir = toplamGelirTF.getText();
        String sifre = musteriSifreTF.getText();
        String adres = mudurAdresTF.getText();
        String mail = musteriMailTF.getText();
        String tel = musteriTelefonTF.getText();
        int temsilci_id = DBislem.getUygunTemsilciID();

        String sorgu = "INSERT INTO kisi(ad, soyad, tc_no, telefon, e_posta, rol_id, sifre, adres) "
                + "VALUES ('" + ad + "', '" + soyad + "', '" + tcno + "', +'" + tel + "', '" + mail + "', 1, '" + sifre + "', '" + adres + "')";
        DBislem.insertQuery(sorgu);

        String sorgu2 = "SELECT * FROM kisi WHERE tc_no ='" + tcno + "'";
        int m_kisi_id = DBislem.getID(sorgu2, this, "kisi_id");

        String sorgu3 = "INSERT INTO musteri (kisi_id, gelir) "
                + "VALUES (" + m_kisi_id + ", " + toplamGelir + ")";
        DBislem.insertQuery(sorgu3);

        int musteri_id = DBislem.getID("SELECT * from musteri WHERE kisi_id=" + m_kisi_id, this, "musteri_id");
        String sorgu4 = "INSERT INTO temsilcinin_musterileri (temsilci_id, musteri_id) "
                + "VALUES (" + temsilci_id + ", " + musteri_id + ")";
        DBislem.insertQuery(sorgu4);

        String sorgu5 = "INSERT INTO hesaplar(musteri_id, hesap_adi, hesap_tur_id, hesap_bakiye) "
                + "VALUES (" + musteri_id + ", '" + "Başlangıç Hesabı" + "', " + "1" + ", 0)";
        DBislem.insertQuery(sorgu5);
        TabloIslem.getInstance().showMusteriTable(musteriTable, temsilci_id, 2);
    }//GEN-LAST:event_musteriEkleButtonActionPerformed

    private void musteriTcnoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musteriTcnoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_musteriTcnoTFActionPerformed

    private void musteriAdTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musteriAdTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_musteriAdTFActionPerformed

    private void temsilciMaasTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temsilciMaasTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temsilciMaasTFActionPerformed

    private void gecikmeFaiziTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gecikmeFaiziTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gecikmeFaiziTFActionPerformed

    private void krediFaiziTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_krediFaiziTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_krediFaiziTFActionPerformed

    private void pbEkleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbEkleButtonActionPerformed
        // TODO add your handling code here:
        String para_birim_adi = paraBirimAdTF.getText();
        double kur_sabiti = Double.parseDouble(kurFiyatTF.getText());

        String sorgu = "INSERT INTO para_birim(\n"
                + "	para_birim_adi, kur_sabiti)\n"
                + "	VALUES ('" + para_birim_adi + "', " + kur_sabiti + ")";
        DBislem.insertQuery(sorgu);
        int p_id = DBislem.getID("Select * from para_birim where kur_sabiti = " + kur_sabiti + " and para_birim_adi='" + para_birim_adi + "'", this, "para_birim_id");
        String sorgu2 = "INSERT INTO hesap_turu("
                + " hesap_tur_adi, para_birim_id)"
                + " VALUES ('" + para_birim_adi + " Hesabı', " + p_id + ");";
        DBislem.insertQuery(sorgu2);

        TabloIslem.getInstance().showParaBirimTable(paraBirimTable);


    }//GEN-LAST:event_pbEkleButtonActionPerformed

    private void kurFiyatTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurFiyatTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kurFiyatTFActionPerformed

    private void paraBirimAdTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paraBirimAdTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paraBirimAdTFActionPerformed

    private void kaydetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetButtonActionPerformed
        // TODO add your handling code here:
        String ad = mudurAdTF.getText();
        String soyad = mudurSoyadTF.getText();
        String tc = mudurTcnoTF.getText();
        String tel = mudurTelefonTF.getText();
        String mail = mudurMailTF.getText();
        String adres = mudurAdresTF.getText();

        String sorgu = "UPDATE kisi\n"
                + "	SET ad='" + ad + "', soyad='" + soyad + "', tc_no='" + tc + "', telefon='" + tel + "', e_posta='" + mail + "', adres='" + adres + "'\n"
                + "	WHERE tc_no='" + mudurTc + "'";
        DBislem.updateQuery(sorgu);
        mudurTc = tc; // eger mudurTc degistirilirse classtakini de guncelle
        mudurAdTF.setEditable(false);
        mudurSoyadTF.setEditable(false);
        mudurTcnoTF.setEditable(false);
        mudurTelefonTF.setEditable(false);
        mudurMailTF.setEditable(false);
        mudurAdresTF.setEditable(false);
    }//GEN-LAST:event_kaydetButtonActionPerformed

    private void duzenleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duzenleButtonActionPerformed
        // TODO add your handling code here:

        mudurAdTF.setEditable(true);
        mudurSoyadTF.setEditable(true);
        mudurTcnoTF.setEditable(true);
        mudurTelefonTF.setEditable(true);
        mudurMailTF.setEditable(true);
        mudurAdresTF.setEditable(true);
    }//GEN-LAST:event_duzenleButtonActionPerformed

    private void mudurMailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mudurMailTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mudurMailTFActionPerformed

    private void mudurTcnoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mudurTcnoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mudurTcnoTFActionPerformed

    private void mudurAdTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mudurAdTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mudurAdTFActionPerformed

    private void pbGuncelleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbGuncelleButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) paraBirimTable.getModel();

        if (paraBirimTable.getSelectedRowCount() == 1) {
            String id = model.getValueAt(paraBirimTable.getSelectedRow(), 0).toString();
            String ad = model.getValueAt(paraBirimTable.getSelectedRow(), 1).toString();
            String kur = model.getValueAt(paraBirimTable.getSelectedRow(), 2).toString();
            String newAd = JOptionPane.showInputDialog(null, "Yeni para birim adı:", ad);
            String newKur = JOptionPane.showInputDialog(null, "Yeni kur:", kur);

            String sorgu = "UPDATE para_birim\n"
                    + "	SET para_birim_adi= '" + newAd + "', kur_sabiti=" + newKur + "\n"
                    + "	WHERE para_birim_id =" + id;
            DBislem.updateQuery(sorgu);
            String sorgu2 = "UPDATE hesap_turu"
                    + "	SET hesap_tur_adi= '" + newAd + " Hesabı'"
                    + "	WHERE para_birim_id =" + id;
            DBislem.updateQuery(sorgu2);

            JOptionPane.showMessageDialog(this, "Para birimi başarıyla güncellendi.");
            TabloIslem.getInstance().showParaBirimTable(paraBirimTable);
        } else {
            JOptionPane.showMessageDialog(this, "Lütfen güncellemek istediğiniz en fazla 1 adet satırı seçin!");
        }


    }//GEN-LAST:event_pbGuncelleButtonActionPerformed

    private void kfDuzenleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kfDuzenleButtonActionPerformed
        // TODO add your handling code here:
        String krediFaiz = krediFaiziTF.getText();
        String newKrediFaiz = JOptionPane.showInputDialog(null, "Yeni kredi faizi:", krediFaiz);
        String sorgu = "UPDATE faiz_oranlari\n"
                + " SET faiz_oran= " + newKrediFaiz + "\n"
                + " WHERE faiz_turu = 'Kredi Faizi'";
        DBislem.updateQuery(sorgu);
        krediFaiziTF.setText(newKrediFaiz);
    }//GEN-LAST:event_kfDuzenleButtonActionPerformed

    private void gfDuzenleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gfDuzenleButtonActionPerformed
        // TODO add your handling code here:
        String gecikmeFaiz = gecikmeFaiziTF.getText();
        String newGecikmeFaiz = JOptionPane.showInputDialog(null, "Yeni gecikme faizi:", gecikmeFaiz);
        String sorgu = "UPDATE faiz_oranlari\n"
                + " SET faiz_oran= " + newGecikmeFaiz + "\n"
                + " WHERE faiz_turu = 'Gecikme Faizi'";
        DBislem.updateQuery(sorgu);
        gecikmeFaiziTF.setText(newGecikmeFaiz);
    }//GEN-LAST:event_gfDuzenleButtonActionPerformed

    private void maasDuzenleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maasDuzenleButtonActionPerformed
        // TODO add your handling code here:
        String maas = temsilciMaasTF.getText();
        String newMaas = JOptionPane.showInputDialog(null, "Yeni kredi faizi:", maas);
        String sorgu = "UPDATE temsilci SET maas=" + newMaas;
        DBislem.updateQuery(sorgu);
        temsilciMaasTF.setText(newMaas);
    }//GEN-LAST:event_maasDuzenleButtonActionPerformed

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        // TODO add your handling code here:
        dispose();
        Login newLogin = new Login();
    }//GEN-LAST:event_logoutLabelMouseClicked

    private void goruntuleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goruntuleButtonActionPerformed
        int limit = Integer.parseInt(islemSayisiTF.getText());
        TabloIslem.getInstance().showIslemTable(islemTable, 0, 3, limit);

    }//GEN-LAST:event_goruntuleButtonActionPerformed

    private void islemSayisiTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_islemSayisiTFKeyTyped
        // TODO add your handling code here:
        char girilenKarakter = evt.getKeyChar();
        if (!Character.isDigit(girilenKarakter)) {
            evt.consume();
        }
    }//GEN-LAST:event_islemSayisiTFKeyTyped

    private void mudurAdTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mudurAdTFKeyTyped
        // TODO add your handling code here:
        char girilenKarakter = evt.getKeyChar();
        if (Character.isDigit(girilenKarakter)) {
            evt.consume();
        }
    }//GEN-LAST:event_mudurAdTFKeyTyped

    private void mudurSoyadTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mudurSoyadTFKeyTyped
        // TODO add your handling code here:
        char girilenKarakter = evt.getKeyChar();
        if (Character.isDigit(girilenKarakter)) {
            evt.consume();
        }
    }//GEN-LAST:event_mudurSoyadTFKeyTyped

    private void mudurTcnoTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mudurTcnoTFKeyTyped
        // TODO add your handling code here:
        char girilenKarakter = evt.getKeyChar();
        if (!Character.isDigit(girilenKarakter)
                || mudurTcnoTF.getText().length() > 10) {
            evt.consume();
        }
    }//GEN-LAST:event_mudurTcnoTFKeyTyped

    private void mudurTelefonTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mudurTelefonTFKeyTyped
        // TODO add your handling code here:
        char girilenKarakter = evt.getKeyChar();
        if (!Character.isDigit(girilenKarakter)
                || mudurTelefonTF.getText().length() > 9) {
            evt.consume();
        }
    }//GEN-LAST:event_mudurTelefonTFKeyTyped

    private void simulationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulationButtonActionPerformed
        // TODO add your handling code here:
        Tarih.getInstance().tarihiIleriAl();
        tarihLabel.setText(Tarih.myFormat.format(Tarih.getAnlikTarih()));

        int musteri_sayisi = DBislem.getMusteriSayisi();
        int[] musteri_id = DBislem.getMusteriler(musteri_sayisi);
        long fark = DBislem.getTarihFark(Tarih.currentDate);

        for (int i = 0; i < musteri_sayisi; i++) {
            int hesap_id = DBislem.getUygunHesapID(musteri_id[i]);

            double aylik_gelir = DBislem.getAylikGelir(musteri_id[i]);
            String sorgu = "UPDATE hesaplar "
                    + "SET hesap_bakiye = hesap_bakiye+" + aylik_gelir
                    + " WHERE hesap_id=" + hesap_id
                    + " and musteri_id=" + musteri_id[i];
            DBislem.paraYatir(sorgu);

            double hesap_bakiye = DBislem.getHesapBakiye(hesap_id);
            String sorgu2 = "INSERT INTO islemler(\n"
                    + "	hedef_hesap_id, islem_tur_id, islem_tarihi, islem_tutari, hedef_bakiye, musteri_id)\n"
                    + "	VALUES (" + hesap_id + ", 7, CURRENT_DATE+" + fark + "," + aylik_gelir + ", " + hesap_bakiye + ", " + musteri_id[i] + ")";
            DBislem.insertQuery(sorgu2);
        }

        double temsilciMaaslari = DBislem.getTemsilciMaas() * DBislem.getTemsilciSayisi();
        String sorgu3 = "INSERT INTO islemler(\n"
                + "	islem_tur_id, islem_tarihi, islem_tutari)\n"
                + "	VALUES (6,CURRENT_DATE+ " + fark + "," + temsilciMaaslari + ")";
        DBislem.insertQuery(sorgu3);

        bankaGiderTF.setText("" + DBislem.getBankaGider());
        bankaGelirTF.setText("" + DBislem.getBankaGelir());


    }//GEN-LAST:event_simulationButtonActionPerformed

    private void toplamGelirTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_toplamGelirTFKeyTyped
        // TODO add your handling code here:
        char girilenKarakter = evt.getKeyChar();
        if (!Character.isDigit(girilenKarakter)) {
            if (girilenKarakter != '.' || toplamGelirTF.getText().contains(".")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_toplamGelirTFKeyTyped

    private void musteriAdTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_musteriAdTFKeyTyped
        // TODO add your handling code here:
        char girilenKarakter = evt.getKeyChar();
        if (Character.isDigit(girilenKarakter)) {
            evt.consume();
        }
    }//GEN-LAST:event_musteriAdTFKeyTyped

    private void musteriSoyadTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_musteriSoyadTFKeyTyped
        // TODO add your handling code here:
        char girilenKarakter = evt.getKeyChar();
        if (Character.isDigit(girilenKarakter)) {
            evt.consume();
        }
    }//GEN-LAST:event_musteriSoyadTFKeyTyped

    private void musteriTcnoTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_musteriTcnoTFKeyTyped
        // TODO add your handling code here:
        char girilenKarakter = evt.getKeyChar();
        if (!Character.isDigit(girilenKarakter)
                || musteriTcnoTF.getText().length() > 10) {
            evt.consume();
        }
    }//GEN-LAST:event_musteriTcnoTFKeyTyped

    private void musteriTelefonTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_musteriTelefonTFKeyTyped
        // TODO add your handling code here:
        char girilenKarakter = evt.getKeyChar();
        if (!Character.isDigit(girilenKarakter)
                || musteriTelefonTF.getText().length() > 9) {
            evt.consume();
        }
    }//GEN-LAST:event_musteriTelefonTFKeyTyped

    private void paraBirimAdTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paraBirimAdTFKeyTyped
        // TODO add your handling code here:
        char girilenKarakter = evt.getKeyChar();
        if (Character.isDigit(girilenKarakter)) {
            evt.consume();
        }
    }//GEN-LAST:event_paraBirimAdTFKeyTyped

    private void kurFiyatTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kurFiyatTFKeyTyped
        // TODO add your handling code here:
        char girilenKarakter = evt.getKeyChar();
        if (!Character.isDigit(girilenKarakter)) {
            if (girilenKarakter != '.' || kurFiyatTF.getText().contains(".")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_kurFiyatTFKeyTyped

    private void bankaGelirTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankaGelirTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bankaGelirTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankaMuduru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankaMuduru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankaMuduru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankaMuduru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankaMuduru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bankaGelirTF;
    private javax.swing.JTextField bankaGiderTF;
    private javax.swing.JButton duzenleButton;
    private javax.swing.JTextField gecikmeFaiziTF;
    private javax.swing.JButton gfDuzenleButton;
    private javax.swing.JButton goruntuleButton;
    private javax.swing.JTextField islemSayisiTF;
    private javax.swing.JTable islemTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLable;
    private javax.swing.JLabel jLable1;
    private javax.swing.JLabel jLable2;
    private javax.swing.JLabel jLable3;
    private javax.swing.JLabel jLable4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton kaydetButton;
    private javax.swing.JButton kfDuzenleButton;
    private javax.swing.JTextField krediFaiziTF;
    private javax.swing.JTextField kurFiyatTF;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JButton maasDuzenleButton;
    private javax.swing.JTextField mudurAdTF;
    private javax.swing.JTextField mudurAdresTF;
    private javax.swing.JTextField mudurMailTF;
    private javax.swing.JTextField mudurSoyadTF;
    private javax.swing.JTextField mudurTcnoTF;
    private javax.swing.JTextField mudurTelefonTF;
    private javax.swing.JTextField musteriAdTF;
    private javax.swing.JTextField musteriAdresTF1;
    private javax.swing.JButton musteriEkleButton;
    private javax.swing.JButton musteriGuncelleButton;
    private javax.swing.JTextField musteriMailTF;
    private javax.swing.JTextField musteriSifreTF;
    private javax.swing.JTextField musteriSoyadTF;
    private javax.swing.JTable musteriTable;
    private javax.swing.JTextField musteriTcnoTF;
    private javax.swing.JTextField musteriTelefonTF;
    private javax.swing.JTextField paraBirimAdTF;
    private javax.swing.JTable paraBirimTable;
    private javax.swing.JButton pbEkleButton;
    private javax.swing.JButton pbGuncelleButton;
    private javax.swing.JButton simulationButton;
    private javax.swing.JLabel tarihLabel;
    private javax.swing.JTextField temsilciMaasTF;
    private javax.swing.JTextField toplamGelirTF;
    // End of variables declaration//GEN-END:variables
}
