
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author trkgrn
 */
public class Temsilci extends javax.swing.JFrame {

    /**
     * Creates new form Temsilci
     */
    private int kisi_id;
    private String tcno;
    private int temsilci_id;

    public Temsilci() {
        initComponents();
    }

    public Temsilci(String tcno, int kisi_id) {
        initComponents();
        setVisible(true);
        this.tcno = tcno;
        this.kisi_id = kisi_id;
        Tarih.getInstance();
        tarihLabel.setText(Tarih.myFormat.format(Tarih.getAnlikTarih()));
        this.temsilci_id = DBislem.getID("SELECT * FROM temsilci WHERE kisi_id=" + kisi_id, this, "temsilci_id");
        TabloIslem.getInstance().showMusteriTable(musteriTable, this.temsilci_id, 1);
        TabloIslem.getInstance().showHesapTalepTable(hesapTalepTable, temsilci_id, 2);
        TabloIslem.getInstance().showKrediTalepTemsilciTable(krediTalepTable, temsilci_id);
        TabloIslem.getInstance().showIslemTemsilciTable(islemTable, temsilci_id, 2);
        initProfile();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        duzenleButton = new javax.swing.JButton();
        kaydetButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        temsilciMaasTF = new javax.swing.JTextField();
        temsilciAdTF = new javax.swing.JTextField();
        temsilciSoyadTF = new javax.swing.JTextField();
        temsilciTcnoTF = new javax.swing.JTextField();
        temsilciTelefonTF = new javax.swing.JTextField();
        temsilciMailTF = new javax.swing.JTextField();
        temsilciAdresTF = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        temsilciMusteriSayisiTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        musteriAdTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        musteriSoyadTF = new javax.swing.JTextField();
        musteriTcnoTF = new javax.swing.JTextField();
        musteriTelefonTF = new javax.swing.JTextField();
        musteriMailTF = new javax.swing.JTextField();
        musteriAdresTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        toplamGelirTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        toplamBakiyeTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        musteriSifreTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        musteriTable = new javax.swing.JTable();
        musteriEkleButton = new javax.swing.JButton();
        musteriGuncelleButton = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        islemTable = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        onaylaHesapButton = new javax.swing.JButton();
        reddetHesapButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        hesapTalepTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        krediTalepTable = new javax.swing.JTable();
        krediOnaylaButton = new javax.swing.JButton();
        krediReddetButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        tarihLabel = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        duzenleButton.setFont(new java.awt.Font("Open Sans", 1, 10)); // NOI18N
        duzenleButton.setText("Düzenle");
        duzenleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duzenleButtonActionPerformed(evt);
            }
        });

        kaydetButton.setFont(new java.awt.Font("Open Sans", 1, 10)); // NOI18N
        kaydetButton.setText("Kaydet");
        kaydetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel8.setText("Maaş");

        temsilciMaasTF.setEditable(false);
        temsilciMaasTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temsilciMaasTFActionPerformed(evt);
            }
        });

        temsilciAdTF.setEditable(false);
        temsilciAdTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temsilciAdTFActionPerformed(evt);
            }
        });
        temsilciAdTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                temsilciAdTFKeyTyped(evt);
            }
        });

        temsilciSoyadTF.setEditable(false);
        temsilciSoyadTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                temsilciSoyadTFKeyTyped(evt);
            }
        });

        temsilciTcnoTF.setEditable(false);
        temsilciTcnoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temsilciTcnoTFActionPerformed(evt);
            }
        });
        temsilciTcnoTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                temsilciTcnoTFKeyTyped(evt);
            }
        });

        temsilciTelefonTF.setEditable(false);
        temsilciTelefonTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                temsilciTelefonTFKeyTyped(evt);
            }
        });

        temsilciMailTF.setEditable(false);

        temsilciAdresTF.setEditable(false);

        jLabel19.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel19.setText("Adres");

        jLabel20.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel20.setText("E-Posta");

        jLabel21.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel21.setText("Telefon No");

        jLabel15.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel15.setText("TCK No");

        jLabel13.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel13.setText("Soyad");

        jLabel2.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel2.setText("Ad");

        temsilciMusteriSayisiTF.setEditable(false);
        temsilciMusteriSayisiTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temsilciMusteriSayisiTFActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel11.setText("Müşteri Sayısı");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(83, 83, 83)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(temsilciTelefonTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(temsilciMailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(83, 83, 83)
                        .addComponent(temsilciAdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(83, 83, 83)
                        .addComponent(temsilciSoyadTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(83, 83, 83)
                        .addComponent(temsilciTcnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(79, 79, 79)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(21, 21, 21)
                            .addComponent(temsilciMaasTF, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addGap(18, 18, 18)
                            .addComponent(temsilciAdresTF, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(23, 23, 23)
                        .addComponent(temsilciMusteriSayisiTF, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(167, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(duzenleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(kaydetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(293, 293, 293))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temsilciAdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(temsilciSoyadTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(temsilciTcnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(temsilciTelefonTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(temsilciMailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(temsilciMaasTF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(temsilciAdresTF, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(temsilciMusteriSayisiTF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(duzenleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kaydetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );

        jTabbedPane1.addTab("Profilim", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel1.setText("Ad");

        musteriAdTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musteriAdTFActionPerformed(evt);
            }
        });
        musteriAdTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                musteriAdTFKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel12.setText("Soyad");

        jLabel14.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel14.setText("TCK No");

        jLabel16.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel16.setText("Telefon No");

        jLabel17.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel17.setText("E-Posta");

        jLabel18.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel18.setText("Adres");

        musteriSoyadTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                musteriSoyadTFKeyTyped(evt);
            }
        });

        musteriTcnoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musteriTcnoTFActionPerformed(evt);
            }
        });
        musteriTcnoTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                musteriTcnoTFKeyTyped(evt);
            }
        });

        musteriTelefonTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                musteriTelefonTFKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel7.setText("Toplam Gelir");

        toplamGelirTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                toplamGelirTFKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel9.setText("Toplam Bakiye");

        toplamBakiyeTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                toplamBakiyeTFKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Noto Sans Cond", 1, 18)); // NOI18N
        jLabel10.setText("Şifre");

        musteriTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Müşteri No", "Temsilci No", "Ad-Soyad", "TCK No", "Telefon No", "E-Mail Adresi", "Adres", "Toplam Bakiye", "Toplam Gelir"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(musteriTable);

        musteriEkleButton.setFont(new java.awt.Font("Open Sans", 1, 10)); // NOI18N
        musteriEkleButton.setText("Yeni Müşteri Ekle");
        musteriEkleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musteriEkleButtonActionPerformed(evt);
            }
        });

        musteriGuncelleButton.setFont(new java.awt.Font("Open Sans", 1, 10)); // NOI18N
        musteriGuncelleButton.setText("Müşteri Güncelle");
        musteriGuncelleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musteriGuncelleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addGap(111, 111, 111)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(musteriSoyadTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(musteriTcnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(145, 145, 145)
                        .addComponent(musteriAdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(musteriSifreTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(toplamGelirTF)
                            .addComponent(toplamBakiyeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(musteriAdresTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musteriTelefonTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musteriMailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(musteriEkleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addComponent(musteriGuncelleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(238, 238, 238))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(musteriAdTF)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(musteriSoyadTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(musteriTcnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(musteriAdresTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(musteriTelefonTF)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(musteriMailTF)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toplamGelirTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toplamBakiyeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(musteriSifreTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(musteriEkleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musteriGuncelleButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {musteriEkleButton, musteriGuncelleButton});

        jTabbedPane2.addTab("Müşteri Ekle/Sil/Güncelle", jPanel4);

        islemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "İşlem No", "Ad-Soyad", "Kaynak", "Hedef", "İşlem Türü", "İşlem Tutarı", "Kaynak Bakiye", "Hedef Bakiye", "İşlem Tarihi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(islemTable);

        jTabbedPane2.addTab("Müşteri Özet", jScrollPane6);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 913, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Müşterilerim", jPanel3);

        onaylaHesapButton.setFont(new java.awt.Font("Open Sans", 1, 10)); // NOI18N
        onaylaHesapButton.setText("TALEP ONAYLA");
        onaylaHesapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onaylaHesapButtonActionPerformed(evt);
            }
        });

        reddetHesapButton.setFont(new java.awt.Font("Open Sans", 1, 10)); // NOI18N
        reddetHesapButton.setText("TALEP REDDET");
        reddetHesapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reddetHesapButtonActionPerformed(evt);
            }
        });

        hesapTalepTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Talep No", "Müşteri No", "Talep Türü", "Hesap Adı", "Hesap Türü", "Durum"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(hesapTalepTable);
        if (hesapTalepTable.getColumnModel().getColumnCount() > 0) {
            hesapTalepTable.getColumnModel().getColumn(0).setResizable(false);
            hesapTalepTable.getColumnModel().getColumn(1).setResizable(false);
            hesapTalepTable.getColumnModel().getColumn(2).setResizable(false);
            hesapTalepTable.getColumnModel().getColumn(3).setResizable(false);
            hesapTalepTable.getColumnModel().getColumn(4).setResizable(false);
            hesapTalepTable.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(onaylaHesapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(reddetHesapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(onaylaHesapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reddetHesapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Hesap Açma / Silme Talepleri", jPanel9);

        krediTalepTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Talep No", "Müşteri No", "Miktar", "Toplam Ay", "Başvuru Durumu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(krediTalepTable);
        if (krediTalepTable.getColumnModel().getColumnCount() > 0) {
            krediTalepTable.getColumnModel().getColumn(0).setResizable(false);
            krediTalepTable.getColumnModel().getColumn(1).setResizable(false);
            krediTalepTable.getColumnModel().getColumn(2).setResizable(false);
            krediTalepTable.getColumnModel().getColumn(3).setResizable(false);
            krediTalepTable.getColumnModel().getColumn(4).setResizable(false);
        }

        krediOnaylaButton.setFont(new java.awt.Font("Open Sans", 1, 10)); // NOI18N
        krediOnaylaButton.setText("TALEP ONAYLA");
        krediOnaylaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                krediOnaylaButtonActionPerformed(evt);
            }
        });

        krediReddetButton.setFont(new java.awt.Font("Open Sans", 1, 10)); // NOI18N
        krediReddetButton.setText("TALEP REDDET");
        krediReddetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                krediReddetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(krediOnaylaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(krediReddetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(krediOnaylaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(krediReddetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Kredi Talepleri", jPanel5);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane1.addTab("Talepler", jPanel8);

        jPanel6.setBackground(new java.awt.Color(255, 102, 0));

        tarihLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        logoutLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\takoy\\Desktop\\Proje-3\\mavenproject1\\src\\main\\java\\com\\mycompany\\mavenproject1\\resim\\logout.png")); // NOI18N
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(tarihLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(logoutLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(tarihLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutLabel)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 918, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void musteriAdTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musteriAdTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_musteriAdTFActionPerformed

    private void musteriTcnoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musteriTcnoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_musteriTcnoTFActionPerformed

    private void musteriEkleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musteriEkleButtonActionPerformed
        // TODO add your handling code here:
        String ad = musteriAdTF.getText();
        String soyad = musteriSoyadTF.getText();
        String tcno = musteriTcnoTF.getText();
        String toplamGelir = toplamGelirTF.getText();
        String toplamBakiye = toplamBakiyeTF.getText();
        String sifre = musteriSifreTF.getText();
        String adres = musteriAdresTF.getText();
        String mail = musteriMailTF.getText();
        String tel = musteriTelefonTF.getText();

        String sorgu = "INSERT INTO kisi(ad, soyad, tc_no, telefon, e_posta, rol_id, sifre, adres) "
                + "VALUES ('" + ad + "', '" + soyad + "', '" + tcno + "', +'" + tel + "', '" + mail + "', 1, '" + sifre + "', '" + adres + "')";
        DBislem.insertQuery(sorgu);

        String sorgu2 = "SELECT * FROM kisi WHERE tc_no ='" + tcno + "'";
        int m_kisi_id = DBislem.getID(sorgu2, this, "kisi_id");

        String sorgu3 = "INSERT INTO musteri (kisi_id, gelir) "
                + "VALUES (" + m_kisi_id + ", " + toplamGelir + ")";
        DBislem.insertQuery(sorgu3);

        int musteri_id = DBislem.getID("SELECT * from musteri WHERE kisi_id=" + m_kisi_id, this, "musteri_id");
        String sorgu4 = "INSERT INTO temsilcinin_musterileri (temsilci_id, musteri_id) "
                + "VALUES (" + this.temsilci_id + ", " + musteri_id + ")";
        DBislem.insertQuery(sorgu4);

        String sorgu5 = "INSERT INTO hesaplar(musteri_id, hesap_adi, hesap_tur_id, hesap_bakiye) "
                + "VALUES (" + musteri_id + ", '" + "Başlangıç Hesabı" + "', " + "1" + ", 0)";
        DBislem.insertQuery(sorgu5);

        TabloIslem.getInstance().showMusteriTable(musteriTable, this.temsilci_id, 1);


    }//GEN-LAST:event_musteriEkleButtonActionPerformed

    private void duzenleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duzenleButtonActionPerformed
        // TODO add your handling code here:

        temsilciAdTF.setEditable(true);
        temsilciSoyadTF.setEditable(true);
        temsilciTcnoTF.setEditable(true);
        temsilciTelefonTF.setEditable(true);
        temsilciMailTF.setEditable(true);
        temsilciAdresTF.setEditable(true);
    }//GEN-LAST:event_duzenleButtonActionPerformed

    private void kaydetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetButtonActionPerformed
        // TODO add your handling code here:
        String ad = temsilciAdTF.getText();
        String soyad = temsilciSoyadTF.getText();
        String tc = temsilciTcnoTF.getText();
        String tel = temsilciTelefonTF.getText();
        String mail = temsilciMailTF.getText();
        String adres = temsilciAdresTF.getText();

        String sorgu = "UPDATE kisi\n"
                + "	SET ad='" + ad + "', soyad='" + soyad + "', tc_no='" + tc + "', telefon='" + tel + "', e_posta='" + mail + "', adres='" + adres + "'\n"
                + "	WHERE tc_no='" + tcno + "'";
        DBislem.updateQuery(sorgu);
        this.tcno = tc; // eger musteriTc degistirilirse classtakini de guncelle

        temsilciAdTF.setEditable(false);
        temsilciSoyadTF.setEditable(false);
        temsilciTcnoTF.setEditable(false);
        temsilciTelefonTF.setEditable(false);
        temsilciMailTF.setEditable(false);
        temsilciAdresTF.setEditable(false);

    }//GEN-LAST:event_kaydetButtonActionPerformed

    private void temsilciAdTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temsilciAdTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temsilciAdTFActionPerformed

    private void temsilciTcnoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temsilciTcnoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temsilciTcnoTFActionPerformed

    private void temsilciMaasTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temsilciMaasTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temsilciMaasTFActionPerformed

    private void temsilciMusteriSayisiTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temsilciMusteriSayisiTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temsilciMusteriSayisiTFActionPerformed

    private void onaylaHesapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onaylaHesapButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) hesapTalepTable.getModel();
        String talepDurum = model.getValueAt(hesapTalepTable.getSelectedRow(), 5).toString();

        if (hesapTalepTable.getSelectedRowCount() == 1
                && talepDurum.equals("Onay Bekleniyor")) {
            String talepTur = model.getValueAt(hesapTalepTable.getSelectedRow(), 2).toString();
            String hesapAd = model.getValueAt(hesapTalepTable.getSelectedRow(), 3).toString();
            String musteriID = model.getValueAt(hesapTalepTable.getSelectedRow(), 1).toString();
            String hesapTur = model.getValueAt(hesapTalepTable.getSelectedRow(), 4).toString();
            int hesapTurID = DBislem.getID("Select * from hesap_turu where hesap_tur_adi= '" + hesapTur + "'", this, "hesap_tur_id");
            String talepId = model.getValueAt(hesapTalepTable.getSelectedRow(), 0).toString();
            int hesapID = DBislem.getID("Select * from hesap_talep where hesap_talep_id= " + talepId, this, "hesap_id");
            String sorgu = "UPDATE hesap_talep SET onay_durum= 'Onaylandı' WHERE hesap_talep_id =" + talepId;
            DBislem.updateQuery(sorgu);
            String sorgu2 = "";
            if (!talepTur.equals("Hesap Açma")) {
                sorgu2 = "DELETE FROM hesaplar WHERE hesap_id=" + hesapID;
                DBislem.deleteQuery(sorgu2);
            } else {
                sorgu2 = "INSERT INTO hesaplar(musteri_id, hesap_adi, hesap_tur_id, hesap_bakiye) "
                        + "VALUES (" + musteriID + ", '" + hesapAd + "', " + hesapTurID + ", 0)";
                DBislem.insertQuery(sorgu2);
            }

            TabloIslem.getInstance().showHesapTalepTable(hesapTalepTable, temsilci_id, 2);
        } else if (hesapTalepTable.getSelectedRowCount() > 1) {
            JOptionPane.showMessageDialog(this, "Tek seferde maksimum bir adet talep seçebilirsiniz.");
        } else if (!talepDurum.equals("Onay Bekleniyor")) {
            JOptionPane.showMessageDialog(this, "Bu talep daha önceden işlenmiş!");
        } else {
            JOptionPane.showMessageDialog(this, "Lütfen onaylamak istediğiniz talebi seçiniz!");
        }

    }//GEN-LAST:event_onaylaHesapButtonActionPerformed

    private void initProfile() {
        String sorgu = "SELECT * FROM kisi where tc_no='" + tcno + "'";
        DBislem dbIslem = new DBislem();
        User user = dbIslem.getUser(sorgu, this);

        temsilciAdTF.setText(user.getAd());
        temsilciSoyadTF.setText(user.getSoyad());
        temsilciTcnoTF.setText(user.getTcNo());
        temsilciTelefonTF.setText(user.getTelefon());
        temsilciMailTF.setText(user.getePosta());
        temsilciAdresTF.setText(user.getAdres());
        temsilciMaasTF.setText("" + DBislem.getTemsilciMaas());
        temsilciMusteriSayisiTF.setText("" + DBislem.getTemsilciMusteriSayisi(temsilci_id));

        temsilciAdTF.setEditable(false);
        temsilciSoyadTF.setEditable(false);
        temsilciTcnoTF.setEditable(false);
        temsilciTelefonTF.setEditable(false);
        temsilciMailTF.setEditable(false);
        temsilciAdresTF.setEditable(false);
    }

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void reddetHesapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reddetHesapButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) hesapTalepTable.getModel();
        String talepDurum = model.getValueAt(hesapTalepTable.getSelectedRow(), 5).toString();

        if (hesapTalepTable.getSelectedRowCount() == 1
                && talepDurum.equals("Onay Bekleniyor")) {
            String talepId = model.getValueAt(hesapTalepTable.getSelectedRow(), 0).toString();
            String sorgu = "UPDATE hesap_talep SET onay_durum= 'Reddedildi' WHERE hesap_talep_id =" + talepId;
            DBislem.updateQuery(sorgu);

            TabloIslem.getInstance().showHesapTalepTable(hesapTalepTable, temsilci_id, 2);
        } else if (hesapTalepTable.getSelectedRowCount() > 1) {
            JOptionPane.showMessageDialog(this, "Tek seferde maksimum bir adet talep seçebilirsiniz.");
        } else if (!talepDurum.equals("Onay Bekleniyor")) {
            JOptionPane.showMessageDialog(this, "Bu talep daha önceden işlenmiş!");
        } else {
            JOptionPane.showMessageDialog(this, "Lütfen reddetmek istediğiniz talebi seçiniz!");
        }

    }//GEN-LAST:event_reddetHesapButtonActionPerformed

    private void krediOnaylaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_krediOnaylaButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) krediTalepTable.getModel();
        String talepDurum = model.getValueAt(krediTalepTable.getSelectedRow(), 4).toString();

        if (krediTalepTable.getSelectedRowCount() == 1
                && talepDurum.equals("Onay Bekleniyor")) {
            String basvuru_id = model.getValueAt(krediTalepTable.getSelectedRow(), 0).toString();
            String musteri_id = model.getValueAt(krediTalepTable.getSelectedRow(), 1).toString();
            String miktar = model.getValueAt(krediTalepTable.getSelectedRow(), 2).toString();
            String toplam_ay = model.getValueAt(krediTalepTable.getSelectedRow(), 3).toString();
            double faiz = DBislem.getFaiz("Kredi Faizi");
            double faizli_miktar = Double.parseDouble(miktar) + Double.parseDouble(miktar) * (faiz / 100);
            double aylik_borc = faizli_miktar / Integer.parseInt(toplam_ay);
            int hesap_id = DBislem.getID("SELECT * from kredi_basvuru where kredi_basvuru_id=" + basvuru_id, this, "hesap_id");
            long fark = DBislem.getTarihFark(Tarih.currentDate);
            String sorgu = "UPDATE kredi_basvuru SET onay_durum= 'Onaylandı' WHERE kredi_basvuru_id =" + basvuru_id;
            DBislem.updateQuery(sorgu);

            String sorgu2 = "INSERT INTO kredi"
                    + "(kredi_basvuru_id, musteri_id, alinan_kredi_toplam, alinan_kredi_toplam_faizli, toplam_ay, kalan_ay) "
                    + "VALUES (" + basvuru_id + ", " + musteri_id + ", " + miktar + ", " + faizli_miktar + ", " + toplam_ay + ", " + toplam_ay + ")";
            DBislem.insertQuery(sorgu2);

            int kredi_id = DBislem.getID("SELECT * from kredi where kredi_basvuru_id=" + basvuru_id, this, "kredi_id");
            String sorgu3 = "";
            for (int i = 0; i < Integer.parseInt(toplam_ay); i++) {
                sorgu3 = "INSERT INTO kredi_odeme(\n"
                        + " kredi_id, aylik_borc, odenen_ay, odendi_mi, gecikme_zammi, kalan_aylik_borc, odeme_aralik)\n"
                        + " VALUES (" + kredi_id + ", " + aylik_borc + ", " + (i + 1) + ", false, 0, " + aylik_borc + ", "
                        + "daterange(CURRENT_DATE + " + (30 * i + 1 + fark) + ", CURRENT_DATE + " + (30 * (i + 1) + 1 + fark) + "))";
                DBislem.insertQuery(sorgu3);
            }

            String sorgu4 = "UPDATE hesaplar SET hesap_bakiye = hesap_bakiye+" + miktar + " WHERE hesap_id=" + hesap_id + " and musteri_id=" + musteri_id;
            DBislem.paraYatir(sorgu4);
            double hesap_bakiye = DBislem.getHesapBakiye(hesap_id);
            String sorgu5 = "INSERT INTO islemler(\n"
                    + "	hedef_hesap_id, islem_tur_id, islem_tarihi, islem_tutari, hedef_bakiye, musteri_id)\n"
                    + "	VALUES (" + hesap_id + ", 4, CURRENT_DATE+ " + fark + "," + miktar + ", " + hesap_bakiye + ", " + musteri_id + ")";
            DBislem.insertQuery(sorgu5);
            TabloIslem.getInstance().showKrediTalepTemsilciTable(krediTalepTable, temsilci_id);
        } else if (hesapTalepTable.getSelectedRowCount() > 1) {
            JOptionPane.showMessageDialog(this, "Tek seferde maksimum bir adet talep seçebilirsiniz.");
        } else if (!talepDurum.equals("Onay Bekleniyor"))
            JOptionPane.showMessageDialog(this, "Bu talep daha önceden işlenmiş!");
        else {
            JOptionPane.showMessageDialog(this, "Lütfen onaylamak istediğiniz talebi seçiniz!");
        }
    }//GEN-LAST:event_krediOnaylaButtonActionPerformed

    private void musteriGuncelleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musteriGuncelleButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) musteriTable.getModel();

        if (musteriTable.getSelectedRowCount() == 1) {
            // burdan devamke
            String musteri_id = model.getValueAt(musteriTable.getSelectedRow(), 0).toString();
            int kisi_id = DBislem.getID("Select * from musteri where musteri_id=" + musteri_id, this, "kisi_id");
            String ad = DBislem.getAd("Select * from kisi where kisi_id=" + kisi_id, this, "ad");
            String soyad = DBislem.getAd("Select * from kisi where kisi_id=" + kisi_id, this, "soyad");
            String tcno = model.getValueAt(musteriTable.getSelectedRow(), 2).toString();
            String telefon = model.getValueAt(musteriTable.getSelectedRow(), 3).toString();
            String mail = model.getValueAt(musteriTable.getSelectedRow(), 4).toString();
            String adres = model.getValueAt(musteriTable.getSelectedRow(), 5).toString();

            String newAd = JOptionPane.showInputDialog(null, "Yeni Ad giriniz:", ad);
            String newSoyad = JOptionPane.showInputDialog(null, "Yeni Soyad giriniz:", soyad);
            String newTcno = JOptionPane.showInputDialog(null, "Yeni TCK No giriniz:", tcno);
            String newTel = JOptionPane.showInputDialog(null, "Yeni Telefon Numarası giriniz:", telefon);
            String newMail = JOptionPane.showInputDialog(null, "Yeni Mail Aderesi giriniz:", mail);
            String newAdres = JOptionPane.showInputDialog(null, "Yeni Adres giriniz:", adres);

            String sorgu = "UPDATE kisi\n"
                    + "	SET ad='" + newAd + "', soyad='" + newSoyad + "', tc_no='" + newTcno + "',"
                    + " telefon='" + newTel + "', e_posta='" + newMail + "', adres='" + newAdres + "'\n"
                    + "	WHERE kisi_id=" + kisi_id;
            DBislem.updateQuery(sorgu);

            JOptionPane.showMessageDialog(this, "Müşteri başarıyla güncellendi.");
            TabloIslem.getInstance().showMusteriTable(musteriTable, temsilci_id, 1);
        } else {
            JOptionPane.showMessageDialog(this, "Lütfen güncellemek istediğiniz en fazla 1 adet satırı seçin!");
        }


    }//GEN-LAST:event_musteriGuncelleButtonActionPerformed

    private void krediReddetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_krediReddetButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) krediTalepTable.getModel();
        String talepDurum = model.getValueAt(krediTalepTable.getSelectedRow(), 4).toString();

        if (krediTalepTable.getSelectedRowCount() == 1
                && talepDurum.equals("Onay Bekleniyor")) {
            String talepId = model.getValueAt(krediTalepTable.getSelectedRow(), 0).toString();
            String sorgu = "UPDATE kredi_basvuru SET onay_durum= 'Reddedildi' WHERE kredi_basvuru_id =" + talepId;
            DBislem.updateQuery(sorgu);

            TabloIslem.getInstance().showKrediTalepTemsilciTable(krediTalepTable, temsilci_id);
        } else if (krediTalepTable.getSelectedRowCount() > 1) {
            JOptionPane.showMessageDialog(this, "Tek seferde maksimum bir adet talep seçebilirsiniz.");
        } else if (!talepDurum.equals("Onay Bekleniyor")) {
            JOptionPane.showMessageDialog(this, "Bu talep daha önceden işlenmiş!");
        } else {
            JOptionPane.showMessageDialog(this, "Lütfen reddetmek istediğiniz talebi seçiniz!");
        }


    }//GEN-LAST:event_krediReddetButtonActionPerformed

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        // TODO add your handling code here:
        dispose();
        Login newLogin = new Login();
    }//GEN-LAST:event_logoutLabelMouseClicked

    private void temsilciAdTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_temsilciAdTFKeyTyped
        // TODO add your handling code here:
        char girilenKarakter = evt.getKeyChar();
        if (Character.isDigit(girilenKarakter)) {
            evt.consume();
        }
    }//GEN-LAST:event_temsilciAdTFKeyTyped

    private void temsilciSoyadTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_temsilciSoyadTFKeyTyped
        // TODO add your handling code here:

        char girilenKarakter = evt.getKeyChar();
        if (Character.isDigit(girilenKarakter)) {
            evt.consume();
        }
    }//GEN-LAST:event_temsilciSoyadTFKeyTyped

    private void temsilciTcnoTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_temsilciTcnoTFKeyTyped
        // TODO add your handling code here:
        char girilenKarakter = evt.getKeyChar();
        if (!Character.isDigit(girilenKarakter)
                || temsilciTcnoTF.getText().length() > 10) {
            evt.consume();
        }
    }//GEN-LAST:event_temsilciTcnoTFKeyTyped

    private void temsilciTelefonTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_temsilciTelefonTFKeyTyped
        // TODO add your handling code here:
        char girilenKarakter = evt.getKeyChar();
        if (!Character.isDigit(girilenKarakter)
                || temsilciTelefonTF.getText().length() > 9) {
            evt.consume();
        }
    }//GEN-LAST:event_temsilciTelefonTFKeyTyped

    private void musteriAdTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_musteriAdTFKeyTyped
        // TODO add your handling code here:
        char girilenKarakter = evt.getKeyChar();
        if (Character.isDigit(girilenKarakter)) {
            evt.consume();
        }


    }//GEN-LAST:event_musteriAdTFKeyTyped

    private void musteriSoyadTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_musteriSoyadTFKeyTyped
        // TODO add your handling code here:
        char girilenKarakter = evt.getKeyChar();
        if (Character.isDigit(girilenKarakter)) {
            evt.consume();
        }
    }//GEN-LAST:event_musteriSoyadTFKeyTyped

    private void musteriTcnoTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_musteriTcnoTFKeyTyped
        // TODO add your handling code here:

        char girilenKarakter = evt.getKeyChar();
        if (!Character.isDigit(girilenKarakter)
                || musteriTcnoTF.getText().length() > 10) {
            evt.consume();
        }

    }//GEN-LAST:event_musteriTcnoTFKeyTyped

    private void musteriTelefonTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_musteriTelefonTFKeyTyped
        // TODO add your handling code here:

        char girilenKarakter = evt.getKeyChar();
        if (!Character.isDigit(girilenKarakter)
                || musteriTelefonTF.getText().length() > 9) {
            evt.consume();
        }
    }//GEN-LAST:event_musteriTelefonTFKeyTyped

    private void toplamGelirTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_toplamGelirTFKeyTyped
        // TODO add your handling code here:
        char girilenKarakter = evt.getKeyChar();
        if (!Character.isDigit(girilenKarakter)) {
            if (girilenKarakter != '.' || toplamGelirTF.getText().contains(".")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_toplamGelirTFKeyTyped

    private void toplamBakiyeTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_toplamBakiyeTFKeyTyped
        // TODO add your handling code here:

        char girilenKarakter = evt.getKeyChar();
        if (!Character.isDigit(girilenKarakter)) {
            if (girilenKarakter != '.' || toplamBakiyeTF.getText().contains(".")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_toplamBakiyeTFKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Temsilci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Temsilci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Temsilci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Temsilci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Temsilci().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton duzenleButton;
    private javax.swing.JTable hesapTalepTable;
    private javax.swing.JTable islemTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JButton kaydetButton;
    private javax.swing.JButton krediOnaylaButton;
    private javax.swing.JButton krediReddetButton;
    private javax.swing.JTable krediTalepTable;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JTextField musteriAdTF;
    private javax.swing.JTextField musteriAdresTF;
    private javax.swing.JButton musteriEkleButton;
    private javax.swing.JButton musteriGuncelleButton;
    private javax.swing.JTextField musteriMailTF;
    private javax.swing.JTextField musteriSifreTF;
    private javax.swing.JTextField musteriSoyadTF;
    private javax.swing.JTable musteriTable;
    private javax.swing.JTextField musteriTcnoTF;
    private javax.swing.JTextField musteriTelefonTF;
    private javax.swing.JButton onaylaHesapButton;
    private javax.swing.JButton reddetHesapButton;
    private javax.swing.JLabel tarihLabel;
    private javax.swing.JTextField temsilciAdTF;
    private javax.swing.JTextField temsilciAdresTF;
    private javax.swing.JTextField temsilciMaasTF;
    private javax.swing.JTextField temsilciMailTF;
    private javax.swing.JTextField temsilciMusteriSayisiTF;
    private javax.swing.JTextField temsilciSoyadTF;
    private javax.swing.JTextField temsilciTcnoTF;
    private javax.swing.JTextField temsilciTelefonTF;
    private javax.swing.JTextField toplamBakiyeTF;
    private javax.swing.JTextField toplamGelirTF;
    // End of variables declaration//GEN-END:variables

}
